---
#   _____                    _   _           _
#  /  ___|                  | | | |         | |
#  \ `--.  ___ ___  _ __ ___| |_| |_   _  __| |
#   `--. \/ __/ _ \| '__/ _ \  _  | | | |/ _` |
#  /\__/ / (_| (_) | | |  __/ | | | |_| | (_| |
#  \____/ \___\___/|_|  \___\_| |_/\__,_|\__,_|
#
# ScoreHud, a Scoreboard plugin for PocketMine-MP
# Copyright (c) 2018 JackMD  < https://github.com/JackMD >
#
# Discord: JackMD#3717
# Twitter: JackMTaylor_
#
# This software is distributed under "GNU General Public License v3.0".
# This license allows you to use it and/or modify it but you are not at
# all allowed to sell this plugin at any cost. If found doing so the
# necessary action required would be taken.
#
# ScoreHud is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License v3.0 for more details.
#
# You should have received a copy of the GNU General Public License v3.0
# along with this program. If not, see
# <https://opensource.org/licenses/GPL-3.0>.
#  -----------------------------------------------------------------------

# DO NOT EDIT THIS VALUE.
# ONLY FOR INTERNAL USE.
config-version: 5

# The amount in seconds after which the Scoreboard would update.
# Increase this value if your server seems to lag.
# Default: 3 seconds.
update-interval: 3

# Set the timezone for {time} to your own preference.
# false - Follow the server/machine time without changes.
# For a list of timezones you can visit: https://secure.php.net/manual/timezones.php
# Example: "America/New_York" - This will set NewYork's time.
timezone: false

# Set the time format that you want to display. Will only work if you add {time} in score-lines in data.yml.
# H - hours
# i - minutes
# s - seconds
# You can fine more information regarding it here: http://php.net/manual/function.date.php
time-format: "H:i:s"

# Set the date format that you want to display. Will only work if you add {date} in score-lines in data.yml.
# d - date (01-31)
# m - month (01-12)
# Y - year (yyyy)
# You can fine more information regarding it here: http://php.net/manual/function.date.php
date-format: "d-m-Y"
...