---
#   _____                    _   _           _
#  /  ___|                  | | | |         | |
#  \ `--.  ___ ___  _ __ ___| |_| |_   _  __| |
#   `--. \/ __/ _ \| '__/ _ \  _  | | | |/ _` |
#  /\__/ / (_| (_) | | |  __/ | | | |_| | (_| |
#  \____/ \___\___/|_|  \___\_| |_/\__,_|\__,_|
#
# ScoreHud, a Scoreboard plugin for PocketMine-MP
# Copyright (c) 2018 JackMD  < https://github.com/JackMD >
#
# Discord: JackMD#3717
# Twitter: JackMTaylor_
#
# This software is distributed under "GNU General Public License v3.0".
# This license allows you to use it and/or modify it but you are not at
# all allowed to sell this plugin at any cost. If found doing so the
# necessary action required would be taken.
#
# ScoreHud is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License v3.0 for more details.
#
# You should have received a copy of the GNU General Public License v3.0
# along with this program. If not, see
# <https://opensource.org/licenses/GPL-3.0>.
#  -----------------------------------------------------------------------

# DO NOT EDIT THIS VALUE.
# ONLY FOR INTERNAL USE.
config-version: 4

# The amount in seconds after which the Scoreboard would update.
# Increase this value if your server seems to lag.
# Default: 3 seconds.
update-interval: 3

# Changing titles of the scoreboard.
# Can be of any number.
server-names:
- "§l§aServer §dName"
- "§l§bServer §cName"
- "§l§cServer §bName"
- "§l§dServer §aName"

# Currently Supported Tags:
# {name}                - Name of the player.
# {money}               - Money of the player. (Requires EconomyAPI by poggit-orphanage).
# {online}              - The number of online players.
# {max_online}          - Max number of players allowed on the server.
# {rank}                - Players current in-game rank/group. (Requires PurePerms by poggit-orphanage).
# {prison_rank}         - Get players Prison rank. (Requires RankUp by Falkirks)
# {item_name}           - Name of the item in players hand.
# {item_id}             - ID of the item in players hand.
# {item_meta}           - Meta/Damage of the item in players hand.
# {item_count}          - Amount of item in the players hand.
# {x}/{y}/{z}           - X/Y/Z coordinate of the player.
# {faction}             - Faction of the player. (Requires FactionsPro by poggit-orphanage).
# {faction_power}       - Power of the faction. (Requires FactionsPro by poggit-orphanage).
# {load}                - Current load on the server (0 - 100%)
# {tps}                 - TPS of the server.
# {level_name}          - Name of the players current level/world.
# {level_folder_name}   - Folder name of the players current level/world.
# {ip}                  - IP of the player.
# {ping}                - Ping of the player.
# {kills}               - Get kill count of a player. (Requires KDR by JackMD).
# {deaths}              - Get death count of a player. (Requires KDR by JackMD).
# {kdr}                 - Get kill to death ratio of a player. (Requires KDR by JackMD).
# {time}                - Show the current time. Please see 'time-format' and 'timezone' above to modify it.
# {cps}                 - Get the clicks per second of a player. (Requires CPS by JackMD).
# {is_state}            - Gets the state of your SkyBlock island. (Requires SkyBlock by GiantQuartz).
# {is_blocks}           - Gets the number of blocks placed on your SkyBlock island. (Requires SkyBlock by GiantQuartz).
# {is_members}          - Gets all the members of you SkyBlock island. (Requires SkyBlock by GiantQuartz).
# {is_size}             - Gets the size of your SkyBlock island. (Requires SkyBlock by GiantQuartz).

# Note: You can find links to the required/supported plugins via the README.md.

# Add the lines that would be shown on the Scoreboard.
# Follow the same pattern as below.
# You can edit the lines already set below and adjust them according to your needs.
# NOTE: You can only set a maximum of 15 lines and no more.
score-lines:
- " §dName: §5{name}"
- " §bOnline: §a{online} §c/ §d{max_online}"

# Set the timezone for {time} to your own preference.
# false - Follow the server/machine time without changes.
# For a list of timezones you can visit: https://secure.php.net/manual/timezones.php
# Example: "America/New_York" - This will set NewYork's time.
timezone: false

# Set the time format that you want to display. Will only work if you add {time} in score-lines.
# H - hours
# i - minutes
# s - seconds
# You can fine more information regarding it here: http://php.net/manual/function.date.php
time-format: "H:i:s"
...
