---
#   _____                    _   _           _
#  /  ___|                  | | | |         | |
#  \ `--.  ___ ___  _ __ ___| |_| |_   _  __| |
#   `--. \/ __/ _ \| '__/ _ \  _  | | | |/ _` |
#  /\__/ / (_| (_) | | |  __/ | | | |_| | (_| |
#  \____/ \___\___/|_|  \___\_| |_/\__,_|\__,_|
#
# ScoreHud, a Scoreboard plugin for PocketMine-MP
# Copyright (c) 2020 Ifera  < https://github.com/Ifera >
#
# Discord: Ifera#3717
# Twitter: JackMTaylor_
#
# This software is distributed under "GNU General Public License v3.0".
# This license allows you to use it and/or modify it but you are not at
# all allowed to sell this plugin at any cost. If found doing so the
# necessary action required would be taken.
#
# ScoreHud is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License v3.0 for more details.
#
# You should have received a copy of the GNU General Public License v3.0
# along with this program. If not, see
# <https://opensource.org/licenses/GPL-3.0>.
#  -----------------------------------------------------------------------

# DO NOT EDIT THIS VALUE.
# ONLY FOR INTERNAL USE.
config-version: 9

# If you want to have different scoreboards for different worlds
# then edit the nested values to suit your needs.
per-world:
  # Set this to true if you want to enable per world scoreboards.
  # Then edit 'scoreboards' key in scorehud.yml to suit your needs.
  active: false

  # If you have 'per-world.active' set to true and you want to display
  # a default scoreboard for a world whose scoreboard you didn't set
  # under 'scoreboards' key in scorehud.yml, then set this to true.
  use-default: false

# Change how time is displayed on your server.
time:
  # Set the timezone to your own preference.
  # false - Follow the server/machine time without changes.
  # For a list of timezones you can visit: https://secure.php.net/manual/timezones.php
  # Example: "America/New_York" - This will set NewYork's time.
  zone: false

  format:
    # Set the time format that you want to display. Will only work
    # if you add {scorehud.time} in score-lines in scorehud.yml.
    # You need ScoreHudX plugin for the tag to work.
    #
    # H - hours
    # i - minutes
    # s - seconds
    #
    # You can fine more information regarding it here:
    # http://php.net/manual/function.date.php
    time: "H:i:s"

    # Set the date format that you want to display. Will only work
    # if you add {scorehud.date} in score-lines in scorehud.yml.
    # You need ScoreHudX plugin for the tag to work.
    #
    # d - date (01-31)
    # m - month (01-12)
    # Y - year (yyyy)
    #
    # You can fine more information regarding it here:
    # http://php.net/manual/function.date.php
    date: "d-m-Y"
...
